---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: postgres-client-pod
  name: postgres-client-pod
spec:
  replicas: 1
  selector:
    app: postgres-client-pod
    deploymentconfig: postgres-client-pod
  strategy:
    resources:
      limits:
        memory: 1Gi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-client-pod
        deploymentconfig: postgres-client-pod
    spec:
      containers:
      - image: riuvshin/postgres-client:latest
        imagePullPolicy: Always
        name: postgres-client-pod
